spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb?useSSL=false&allowPublicKeyRetrieval=True&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    banner-mode: console


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      springframework: ERROR